[project]
name = "fintda"
version = "0.1.0"
description = "Basics tools and utilities for financial topological data analysis (TDA)."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.2",
    "scikit-learn>=1.8.0",
    "scikit-tda>=1.1.1",
    "scipy>=1.17.0",
]
